export const DEFAULT_MODEL_CHOICES = [
  "gpt-5.2",
  "gpt-5.1",
  "gpt-5-mini",
  "gpt-5-nano",
  "gpt-5",
  "gpt-4.1",
  "gpt-4.1-mini",
  "gpt-4o",
  "gpt-4o-mini",
  "o4-mini",
  "o3-mini"
];

export const DEFAULT_SETTINGS = {
  schemaVersion: 1,
  hintModel: "gpt-5-mini",
  analyzeModel: "gpt-5-mini",
  noteModel: "gpt-5-mini",
  responseLanguage: "en",
  uiLanguage: "en",
  uiLanguageExplicit: false,
  appearance: "system",
  confirmBeforeAi: false,
  confirmBeforeAiExplicit: false,
  includeProblemContextByDefault: true,
  includeSelectionByDefault: false,
  saveCodeByDefault: true,
  allowHintTextStorage: false,
  allowAnswerInUnsolvedNotes: false,
  autoSaveSubmissionSnapshots: true,
  cloudSync: false,
  privacyNoticeShown: false,
  openaiDisclosureShown: false,
  chatFontSize: 14,
  killSwitch: {
    leetcodeEnabled: true,
    programmersEnabled: true,
    aiHintingEnabled: true,
    selectedContextEnabled: true,
    noteSavingEnabled: true,
    message: ""
  }
};

export const HINT_CATEGORIES = [
  "approach_selection",
  "constraint_analysis",
  "data_structure_selection",
  "list_usage",
  "set_usage",
  "dict_usage",
  "hashmap_usage",
  "complement_pattern",
  "heap_usage",
  "queue_usage",
  "stack_usage",
  "sorting",
  "sorting_criteria",
  "duplicate_handling",
  "pair_enumeration",
  "combination_indexing",
  "loop_usage",
  "math_formula",
  "bitwise_operation",
  "two_pointer",
  "sliding_window",
  "binary_search",
  "binary_search_boundary",
  "bfs",
  "dfs",
  "visited_timing",
  "grid_boundary_check",
  "dp_state_definition",
  "dp_transition",
  "dp_initialization",
  "greedy_choice",
  "edge_case",
  "off_by_one",
  "return_value_misunderstanding",
  "python_api_usage",
  "javascript_api_usage",
  "time_complexity",
  "space_complexity",
  "output_format",
  "syntax_error",
  "runtime_error"
];

export const HINT_CATEGORY_LABELS = {
  approach_selection: { ko: "접근 방향 선택", en: "Approach selection" },
  constraint_analysis: { ko: "조건 해석", en: "Constraint reading" },
  data_structure_selection: { ko: "자료구조 선택", en: "Data structure choice" },
  list_usage: { ko: "리스트 사용", en: "List usage" },
  set_usage: { ko: "집합 사용", en: "Set usage" },
  dict_usage: { ko: "딕셔너리 사용", en: "Dictionary usage" },
  hashmap_usage: { ko: "해시맵 활용", en: "Hash map usage" },
  complement_pattern: { ko: "짝/보수 관계", en: "Complement relationship" },
  heap_usage: { ko: "힙 활용", en: "Heap usage" },
  queue_usage: { ko: "큐 활용", en: "Queue usage" },
  stack_usage: { ko: "스택 활용", en: "Stack usage" },
  sorting: { ko: "정렬 필요성", en: "Sorting need" },
  sorting_criteria: { ko: "정렬 기준", en: "Sorting criteria" },
  duplicate_handling: { ko: "중복 처리", en: "Duplicate handling" },
  pair_enumeration: { ko: "쌍 탐색", en: "Pair enumeration" },
  combination_indexing: { ko: "조합 인덱싱", en: "Combination indexing" },
  loop_usage: { ko: "반복 구조", en: "Loop structure" },
  math_formula: { ko: "수식 모델링", en: "Formula modeling" },
  bitwise_operation: { ko: "비트 연산", en: "Bitwise operation" },
  two_pointer: { ko: "투 포인터", en: "Two pointers" },
  sliding_window: { ko: "슬라이딩 윈도우", en: "Sliding window" },
  binary_search: { ko: "이분 탐색", en: "Binary search" },
  binary_search_boundary: { ko: "이분 탐색 경계", en: "Binary-search boundary" },
  bfs: { ko: "BFS 탐색", en: "BFS traversal" },
  dfs: { ko: "DFS 탐색", en: "DFS traversal" },
  visited_timing: { ko: "방문 처리 시점", en: "Visited timing" },
  grid_boundary_check: { ko: "격자 경계 확인", en: "Grid boundary check" },
  dp_state_definition: { ko: "DP 상태 정의", en: "DP state definition" },
  dp_transition: { ko: "DP 점화식", en: "DP transition" },
  dp_initialization: { ko: "DP 초기값", en: "DP initialization" },
  greedy_choice: { ko: "그리디 선택", en: "Greedy choice" },
  edge_case: { ko: "예외 케이스", en: "Edge case" },
  off_by_one: { ko: "인덱스/경계 한 칸 차이", en: "Off-by-one boundary" },
  return_value_misunderstanding: { ko: "반환값 오해", en: "Return value mismatch" },
  python_api_usage: { ko: "Python API 사용", en: "Python API usage" },
  javascript_api_usage: { ko: "JavaScript API 사용", en: "JavaScript API usage" },
  time_complexity: { ko: "시간 복잡도", en: "Time complexity" },
  space_complexity: { ko: "공간 복잡도", en: "Space complexity" },
  output_format: { ko: "출력 형식", en: "Output format" },
  syntax_error: { ko: "문법 오류", en: "Syntax error" },
  runtime_error: { ko: "실행 오류", en: "Runtime error" }
};

export const STORAGE_KEYS = {
  settings: "settings",
  apiCredential: "apiCredential",
  sessionsByUrl: "sessionsByUrl",
  hintEvents: "hintEvents",
  learningEvents: "learningEvents",
  savedNotes: "savedNotes",
  codeSnapshots: "codeSnapshots",
  problemMetadata: "problemMetadata",
  coachThreads: "coachThreads"
};

export const AI_OUTPUT_MARKER = "---metadata---";

export const REQUEST_KINDS = {
  hint: "hint",
  explainLine: "explainLine",
  analyze: "analyze",
  chatCoach: "chat_coach",
  debugLab: "debug_lab",
  note: "note",
  codeDiff: "code_diff",
  nextCodeHint: "next_code_hint"
};
