export const SIDEPANEL_SELECTORS = {
  pageStatus: "#page-status",
  eligibilityPill: "#eligibility-pill",
  apiPill: "#api-pill",
  problemMeta: "#problem-meta",
  syncState: "#sync-state",
  blockedReason: "#blocked-reason",
  timerState: "#timer-state",
  timerTime: "#timer-time",
  timerDuration: "#timer-duration",
  timerCustomMinutes: "#timer-custom-minutes",
  timerStart: "#timer-start",
  timerPause: "#timer-pause",
  timerReset: "#timer-reset",
  timerFinish: "#timer-finish",
  timerAlarm: "#timer-alarm",
  uiLanguage: "#ui-language",
  problemDescriptionDisplay: "#problem-description-display",
  problemContext: "#problem-context",
  includeProblemContext: "#include-problem-context",
  language: "#language",
  code: "#code",
  codeLineNumbers: "#code-line-numbers",
  codeEditorFilename: "#code-editor-filename",
  codeSaveTime: "#code-save-time",
  codeCopyBtn: "#code-copy-btn",
  codeFormatBtn: "#code-format-btn",
  codeSelOverlay: "#code-sel-overlay",
  codeSelBtn: "#code-sel-btn",
  userNote: "#user-note",
  saveCode: "#save-code",
  quickChecks: "#quick-checks",
  debugExplainLine: "#debug-explain-line",
  debugTestcaseExpChip: "#debug-testcase-exp",
  debugTestcaseExpPanel: "#debug-testcase-exp-panel",
  debugTcAiSuggest: "#debug-tc-ai-suggest",
  debugTcSuggestedList: "#debug-tc-suggested-list",
  debugTcCustomInput: "#debug-tc-custom-input",
  debugTcCustomExpected: "#debug-tc-custom-expected",
  debugTcAddCustom: "#debug-tc-add-custom",
  debugTcUserList: "#debug-tc-user-list",
  debugEfficiency: "#debug-efficiency",
  debugLabChatInput: "#debug-lab-chat-input",
  debugLabSend: "#debug-lab-send",
  debugLabOutput: "#debug-lab-output",
  debugLabState: "#debug-lab-state",
  output: "#output",
  codeSuggestionPanel: "#code-suggestion-panel",
  codeSuggestion: "#code-suggestion",
  copyCodeSuggestion: "#copy-code-suggestion",
  streamState: "#stream-state",
  metadataTags: "#metadata-tags",
  noteOutput: "#note-output",
  notePreview: "#note-preview",
  noteLibrary: "#note-library",
  manualNoteCreate: "#manual-note-create",
  noteStreamState: "#note-stream-state",
  noteEditorPanel: "#note-editor-panel",
  noteEditorTitle: "#note-editor-title",
  noteEditorContent: "#note-editor-content",
  noteEditorStatusChip: "#note-editor-status-chip",
  closeNoteEditor: "#close-note-editor",
  noteModal: "#note-modal",
  closeNoteModal: "#close-note-modal",
  noteModalTitle: "#note-modal-title",
  noteModalSubtitle: "#note-modal-subtitle",
  noteModalBody: "#note-modal-body",
  codeDiffModal: "#code-diff-modal",
  closeCodeDiffModal: "#close-code-diff-modal",
  codeDiffSubtitle: "#code-diff-subtitle",
  codeDiffState: "#code-diff-state",
  diffFailedCode: "#diff-failed-code",
  diffPassedCode: "#diff-passed-code",
  codeDiffReview: "#code-diff-review",
  saveCodeDiffReview: "#save-code-diff-review",
  refresh: "#refresh",
  codeTab: "#code-tab",
  historyTab: "#history-tab",
  railToggle: "#rail-toggle",
  railCollapse: "#rail-collapse",
  railMore: "#rail-more",
  timerTab: "#timer-tab",
  timerPopup: "#timer-popup",
  railAccount: "#rail-account",
  railMorePopover: "#rail-more-popover",
  coachChatTranscript: "#coach-chat-transcript",
  coachProblemCard: "#coach-problem-card",
  coachProblemSummary: "#coach-problem-summary",
  coachContextStatus: "#coach-context-status",
  coachOpenCodeView: "#coach-open-code-view",
  composerContextStrip: "#composer-context-strip",
  composerModelRow: "#composer-model-row",
  composerModelSelect: "#composer-model-select",
  composerProblemTitle: "#composer-problem-title",
  composerPlatformFavicon: "#composer-platform-favicon",
  chatInput: "#chat-input",
  chatSend: "#chat-send",
  accountAvatarImg: "#account-avatar-img",
  accountModal: "#account-modal",
  apikeyModal: "#apikey-modal",
  confirmModal: "#confirm-modal",
  confirmTitle: "#confirm-title",
  confirmMessage: "#confirm-message",
  confirmClose: "#confirm-close",
  confirmCancel: "#confirm-cancel",
  confirmOk: "#confirm-ok",
  settingsModal: "#settings-modal",
  closeSettings: "#close-settings",
  hint: "#hint",
  hintLevel: "#hint-level",
  explainLine: "#explain-line",
  analyze: "#analyze",
  nextCodeHint: "#next-code-hint",
  generateNote: "#generate-note",
  saveNote: "#save-note",
  copyNote: "#copy-note",
  exportMarkdown: "#export-markdown",
  coachTab: "#coach-tab",
  noteTab: "#note-tab",
  reviewTab: "#review-tab",
  coachView: "#coach-view",
  noteView: "#note-view",
  reviewView: "#review-view",
  settingsState: "#settings-state",
  settingsHintModel: "#settings-hint-model",
  settingsAnalyzeModel: "#settings-analyze-model",
  settingsNoteModel: "#settings-note-model",
  settingsResponseLanguage: "#settings-response-language",
  settingsUiLanguage: "#settings-ui-language",
  settingsChatFontSize: "#settings-chat-font-size",
  settingsConfirmBeforeAi: "#settings-confirm-before-ai",
  settingsIncludeProblemContext: "#settings-include-problem-context",
  settingsSaveCode: "#settings-save-code",
  settingsStoreHintText: "#settings-store-hint-text",
  settingsAllowUnsolvedAnswer: "#settings-allow-unsolved-answer",
  settingsAutoSaveSubmissions: "#settings-auto-save-submissions",
  settingsCloudSync: "#settings-cloud-sync",
  saveSettings: "#save-settings",
  activeProblemTitle: "#active-problem-title",
  activeProblemLink: "#active-problem-link",
  activeProblemPlatform: "#active-problem-platform",
  activeProblemDifficulty: "#active-problem-difficulty",
  activeProblemLanguage: "#active-problem-language",
  activeProblemStats: "#active-problem-stats",
  activeProblemAttempts: "#active-problem-attempts",
  activeProblemAcceptance: "#active-problem-acceptance",
  sessionCount: "#session-count",
  hintCount: "#hint-count",
  noteCount: "#note-count",
  snapshotCount: "#snapshot-count",
  historySearch: "#history-search",
  historyPlatformFilter: "#history-platform-filter",
  historyStatusFilter: "#history-status-filter",
  historySort: "#history-sort",
  historySelectAll: "#history-select-all",
  historySelectionCount: "#history-selection-count",
  deleteSelectedHistory: "#delete-selected-history",
  deleteAllHistory: "#delete-all-history",
  noteSearch: "#note-search",
  notePlatformFilter: "#note-platform-filter",
  noteStatusFilter: "#note-status-filter",
  noteSort: "#note-sort",
  noteSelectAll: "#note-select-all",
  noteSelectedCount: "#note-selected-count",
  noteTotalCount: "#note-total-count",
  deleteSelectedNotes: "#delete-selected-notes",
  notePagination: "#note-pagination",
  reviewPlanner: "#review-planner",
  topProblemTypes: "#top-problem-types",
  topCautionPoints: "#top-caution-points",
  topImplementationHints: "#top-implementation-hints",
  historyWeaknessRadar: "#history-weakness-radar",
  recentSessions: "#recent-sessions",
  hsAttempts: "#hs-attempts",
  hsSolved: "#hs-solved",
  hsNotes: "#hs-notes",
  hsAccuracy: "#hs-accuracy",
  hsHintRatio: "#hs-hint-ratio",
  hsHintRatioDelta: "#hs-hint-ratio-delta",
  hsReviewRate: "#hs-review-rate",
  hsReviewRateDelta: "#hs-review-rate-delta",
  historyTrendChart: "#history-trend-chart",
  weaknessTop5Body: "#weakness-top5-body",
  historyBarChart: "#history-bar-chart",
  codeHistory: "#code-history",
  noteDetailPanel: "#note-detail-panel",
  noteDetailBack: "#note-detail-back",
  noteDetailProblemLink: "#note-detail-problem-link",
  noteDetailTitle: "#note-detail-title",
  noteDetailPlatform: "#note-detail-platform",
  noteDetailStatus: "#note-detail-status",
  noteDetailTime: "#note-detail-time",
  noteDetailTags: "#note-detail-tags",
  noteDetailBody: "#note-detail-body",
  noteDetailRetry: "#note-detail-retry",
  noteDetailStudy: "#note-detail-study",
  reviewAddBtn: "#review-add-btn",
  reviewAddModal: "#review-add-modal",
  reviewAddSource: "#review-add-source",
  reviewAddSearch: "#review-add-search",
  reviewAddResults: "#review-add-results",
  reviewAddStartDate: "#review-add-start-date",
  reviewAddConfirm: "#review-add-confirm",
  reviewAddCancel: "#review-add-cancel"
};

export const SIDEPANEL_COLLECTION_SELECTORS = {
  tabButtons: ".tab"
};

const OPTIONAL_ELEMENT_KEYS = new Set([
  "saveCode",
  "settingsSaveCode",
  "accountAvatarImg",
  "apikeyModal",
  "noteOutput",
  "notePreview",
  "exportMarkdown",
  "noteEditorPanel",
  "noteEditorTitle",
  "noteEditorContent",
  "noteEditorStatusChip",
  "closeNoteEditor",
  "codeSaveTime",
  "codeCopyBtn",
  "codeFormatBtn",
  "codeSelBtn",
  "eligibilityPill",
  "apiPill",
  "debugTcAnalyze",
  "activeProblemTitle",
  "activeProblemLink",
  "activeProblemPlatform",
  "activeProblemDifficulty",
  "activeProblemLanguage",
  "activeProblemStats",
  "activeProblemAttempts",
  "activeProblemAcceptance",
  "noteSearch",
  "notePlatformFilter",
  "noteStatusFilter",
  "noteSort",
  "noteSelectAll",
  "noteSelectedCount",
  "noteTotalCount",
  "deleteSelectedNotes",
  "notePagination",
  "noteDetailPanel",
  "noteDetailBack",
  "noteDetailProblemLink",
  "noteDetailTitle",
  "noteDetailPlatform",
  "noteDetailStatus",
  "noteDetailTime",
  "noteDetailTags",
  "noteDetailBody",
  "noteDetailRetry",
  "noteDetailStudy",
  "topProblemTypes",
  "topCautionPoints",
  "topImplementationHints",
  "hsAttempts",
  "hsSolved",
  "hsNotes",
  "hsAccuracy",
  "hsHintRatio",
  "hsHintRatioDelta",
  "hsReviewRate",
  "hsReviewRateDelta",
  "historyTrendChart",
  "weaknessTop5Body",
  "historyBarChart",
  "reviewAddBtn",
  "reviewAddModal",
  "reviewAddSearch",
  "reviewAddResults",
  "reviewAddStartDate",
  "reviewAddConfirm",
  "reviewAddCancel",
  "composerPlatformFavicon"
]);

export function getSidepanelElements(documentRef = document) {
  const elements = Object.fromEntries(
    Object.entries(SIDEPANEL_SELECTORS).map(([key, selector]) => [key, documentRef.querySelector(selector)])
  );
  Object.entries(SIDEPANEL_COLLECTION_SELECTORS).forEach(([key, selector]) => {
    elements[key] = [...documentRef.querySelectorAll(selector)];
  });
  return elements;
}

export function assertRequiredElements(elements) {
  const missing = Object.keys(SIDEPANEL_SELECTORS).filter((key) => !OPTIONAL_ELEMENT_KEYS.has(key) && !elements[key]);
  const missingCollections = Object.keys(SIDEPANEL_COLLECTION_SELECTORS).filter((key) => !elements[key]?.length);
  missing.push(...missingCollections);
  if (missing.length) {
    throw new Error(`Missing sidepanel elements: ${missing.join(", ")}`);
  }
  return elements;
}

let _toastTimeout = null;

export function showToast(message, type = "success", documentRef = document) {
  documentRef.querySelector(".toast")?.remove();
  clearTimeout(_toastTimeout);
  const toast = documentRef.createElement("div");
  toast.className = `toast toast--${type}`;
  toast.textContent = message;
  documentRef.body.appendChild(toast);
  requestAnimationFrame(() => toast.classList.add("toast--visible"));
  _toastTimeout = setTimeout(() => {
    toast.classList.remove("toast--visible");
    toast.addEventListener("transitionend", () => toast.remove(), { once: true });
  }, 2500);
}
