const SPECS = [
  ["constraint_check", "problem_understanding", "제약 조건", "Constraints"],
  ["objective_check", "problem_understanding", "목표 조건", "Problem objective"],
  ["input_shape_check", "problem_understanding", "입력 형태", "Input shape"],
  ["output_requirement_check", "problem_understanding", "출력 요구", "Output format"],
  ["example_generalization_check", "problem_understanding", "예시 일반화", "Generalizing examples"],
  ["terminology_check", "problem_understanding", "문제 용어", "Problem terms"],
  ["edge_case_check", "edge_cases", "예외 케이스", "Edge cases"],
  ["empty_input_check", "edge_cases", "빈 입력", "Empty input"],
  ["single_element_check", "edge_cases", "원소 1개", "Single element"],
  ["duplicate_case_check", "edge_cases", "중복 케이스", "Duplicates"],
  ["negative_number_check", "edge_cases", "음수 케이스", "Negative numbers"],
  ["zero_value_check", "edge_cases", "0 값", "Zero values"],
  ["large_input_check", "edge_cases", "큰 입력", "Large inputs"],
  ["hidden_case_check", "edge_cases", "숨은 케이스", "Hidden cases"],
  ["boundary_check", "boundary_index", "경계 조건", "Boundary conditions"],
  ["off_by_one_risk", "boundary_index", "한 칸 차이", "Off-by-one"],
  ["inclusive_exclusive_check", "boundary_index", "포함/미포함 경계", "Inclusive vs exclusive"],
  ["start_end_pointer_check", "boundary_index", "시작/끝 포인터", "Start/end pointer"],
  ["loop_bound_check", "boundary_index", "반복 범위", "Loop bounds"],
  ["index_mapping_check", "boundary_index", "인덱스 매핑", "Index mapping"],
  ["brute_force_trap_check", "algorithm_choice", "완전탐색 함정", "Brute-force trap"],
  ["pattern_choice_check", "algorithm_choice", "풀이 패턴", "Algorithm pattern"],
  ["invariant_check", "algorithm_choice", "불변식", "Invariant"],
  ["proof_of_greedy_check", "algorithm_choice", "그리디 근거", "Greedy justification"],
  ["subproblem_definition_check", "algorithm_choice", "부분 문제 정의", "Subproblem definition"],
  ["state_definition_check", "state_dp", "상태 정의", "State definition"],
  ["state_transition_check", "state_dp", "상태 전이", "State transition"],
  ["initial_state_check", "state_dp", "초기 상태", "Initial state"],
  ["state_reset_check", "state_dp", "상태 초기화", "State reset"],
  ["mutation_side_effect_check", "state_dp", "값 변경 부작용", "Mutation side effects"],
  ["recursion_base_case_check", "state_dp", "재귀 종료 조건", "Recursion base case"],
  ["visited_timing_check", "graph_traversal", "방문 처리 시점", "Visit order"],
  ["revisit_condition_check", "graph_traversal", "재방문 조건", "Revisit condition"],
  ["cycle_handling_check", "graph_traversal", "사이클 처리", "Cycle handling"],
  ["connected_component_check", "graph_traversal", "연결 요소", "Connected components"],
  ["graph_direction_check", "graph_traversal", "그래프 방향", "Graph direction"],
  ["weighted_edge_check", "graph_traversal", "가중치", "Weighted edges"],
  ["complexity_check", "complexity", "복잡도", "Complexity"],
  ["time_complexity_check", "complexity", "시간 복잡도", "Time complexity"],
  ["space_complexity_check", "complexity", "공간 복잡도", "Space complexity"],
  ["hidden_nested_loop_check", "complexity", "숨은 중첩 반복", "Hidden nested loop"],
  ["precomputation_check", "complexity", "전처리", "Precomputation"],
  ["sort_key_check", "ordering", "정렬 기준", "Sort key"],
  ["tie_break_check", "ordering", "동률 처리", "Tie-breaking"],
  ["order_stability_check", "ordering", "순서 안정성", "Order stability"],
  ["duplicate_handling_check", "ordering", "중복 처리", "Duplicate handling"],
  ["return_format_check", "output_api", "반환 형식", "Return format"],
  ["return_value_check", "output_api", "반환값", "Return value"],
  ["type_conversion_check", "output_api", "타입 변환", "Type conversion"],
  ["null_handling_check", "output_api", "NULL/None 처리", "Null handling"],
  ["api_contract_check", "output_api", "API 계약", "API contract"],
  ["sample_only_check", "testing_behavior", "예시만 확인하지 않기", "Don't test only examples"],
  ["run_vs_submit_check", "testing_behavior", "실행/제출 차이", "Run vs submit"],
  ["regression_case_check", "testing_behavior", "재발 케이스", "Regression cases"],
  ["sql_null_semantics_check", "sql", "SQL NULL 의미", "SQL NULL semantics"],
  ["sql_join_cardinality_check", "sql", "SQL JOIN 행 수", "SQL JOIN cardinality"],
  ["sql_grouping_granularity_check", "sql", "SQL GROUP BY 단위", "SQL grouping granularity"],
  ["sql_aggregate_filter_check", "sql", "SQL 집계 필터", "SQL aggregate filter"],
  ["sql_date_boundary_check", "sql", "SQL 날짜 경계", "SQL date boundary"]
];

export const CAUTION_POINT_TAGS = SPECS.map(([id, group, ko, en]) => ({
  id,
  group,
  label: { ko, en },
  description: {
    ko: `${ko}이 필요한 상황인지 표시합니다.`,
    en: `Marks that this situation needs a ${en.toLowerCase()}.`
  }
}));
