const SPECS = [
  ["approach_selection", "reasoning_bridge", "접근 방향 선택", "Approach selection"],
  ["constraint_analysis", "reasoning_bridge", "조건 해석", "Constraint reading"],
  ["data_structure_selection", "reasoning_bridge", "자료구조 선택", "Data structure choice"],
  ["list_usage", "data_structure_usage", "리스트 사용", "List usage"],
  ["set_usage", "data_structure_usage", "집합 사용", "Set usage"],
  ["dict_usage", "data_structure_usage", "딕셔너리 사용", "Dictionary usage"],
  ["hashmap_usage", "data_structure_usage", "해시맵 활용", "Hash map usage"],
  ["heap_usage", "data_structure_usage", "힙 활용", "Heap usage"],
  ["queue_usage", "data_structure_usage", "큐 활용", "Queue usage"],
  ["stack_usage", "data_structure_usage", "스택 활용", "Stack usage"],
  ["deque_usage", "data_structure_usage", "덱 활용", "Deque usage"],
  ["sorting", "control_ordering", "정렬 필요성", "Sorting need"],
  ["sorting_criteria", "control_ordering", "정렬 기준", "Sorting criteria"],
  ["duplicate_handling", "control_ordering", "중복 처리", "Duplicate handling"],
  ["complement_pattern", "control_ordering", "짝/보수 관계", "Complement relationship"],
  ["pair_enumeration", "control_ordering", "쌍 탐색", "Pair enumeration"],
  ["combination_indexing", "control_ordering", "조합 인덱싱", "Combination indexing"],
  ["loop_usage", "control_flow", "반복 구조", "Loop structure"],
  ["loop_structure", "control_flow", "반복문 구성", "Loop construction"],
  ["nested_loop_control", "control_flow", "중첩 반복 제어", "Nested loop control"],
  ["early_return", "control_flow", "조기 반환", "Early return"],
  ["recursion_structure", "control_flow", "재귀 구조", "Recursion structure"],
  ["math_formula", "value_modeling", "수식 모델링", "Formula modeling"],
  ["bitwise_operation", "value_modeling", "비트 연산", "Bitwise operation"],
  ["type_conversion", "value_modeling", "타입 변환", "Type conversion"],
  ["return_value_handling", "value_modeling", "반환값 처리", "Return value"],
  ["return_value_misunderstanding", "value_modeling", "반환값 오해", "Return value mismatch"],
  ["output_format", "value_modeling", "출력 형식", "Output format"],
  ["two_pointer", "algorithm_detail", "투 포인터 구현", "Two-pointer implementation"],
  ["sliding_window", "algorithm_detail", "슬라이딩 윈도우 구현", "Sliding-window implementation"],
  ["binary_search", "algorithm_detail", "이분 탐색 구현", "Binary-search implementation"],
  ["binary_search_boundary", "algorithm_detail", "이분 탐색 경계", "Binary-search boundary"],
  ["bfs", "algorithm_detail", "BFS 구현", "BFS implementation"],
  ["dfs", "algorithm_detail", "DFS 구현", "DFS implementation"],
  ["visited_timing", "algorithm_detail", "방문 처리 시점", "Visited timing"],
  ["grid_boundary_check", "algorithm_detail", "격자 경계", "Grid boundary"],
  ["dp_state_definition", "algorithm_detail", "DP 상태 정의", "DP state definition"],
  ["dp_transition", "algorithm_detail", "DP 점화식", "DP transition"],
  ["dp_initialization", "algorithm_detail", "DP 초기값", "DP initialization"],
  ["greedy_choice", "algorithm_detail", "그리디 선택", "Greedy choice"],
  ["edge_case", "legacy_compatibility", "예외 케이스", "Edge case"],
  ["off_by_one", "legacy_compatibility", "인덱스 한 칸 차이", "Off-by-one"],
  ["time_complexity", "legacy_compatibility", "시간 복잡도", "Time complexity"],
  ["space_complexity", "legacy_compatibility", "공간 복잡도", "Space complexity"],
  ["python_api_usage", "language_api", "Python API 사용", "Python API usage"],
  ["javascript_api_usage", "language_api", "JavaScript API 사용", "JavaScript API usage"],
  ["string_api_usage", "language_api", "문자열 API 사용", "String API usage"],
  ["collection_api_usage", "language_api", "컬렉션 API 사용", "Collection API usage"],
  ["comparator_usage", "language_api", "비교 함수 사용", "Comparator usage"],
  ["syntax_error", "runtime", "문법 오류", "Syntax error"],
  ["runtime_error", "runtime", "실행 오류", "Runtime error"],
  ["null_or_undefined_handling", "runtime", "NULL/undefined 처리", "Null/undefined"]
];

export const IMPLEMENTATION_HINT_TAGS = SPECS.map(([id, group, ko, en]) => ({
  id,
  group,
  label: { ko, en },
  description: {
    ko: `${ko}와 관련된 코드 작성 힌트입니다.`,
    en: `Code-writing hint related to ${en.toLowerCase()}.`
  }
}));
