const SPECS = [
  ["array", "core_data_structure", "배열", "Array"],
  ["string", "core_data_structure", "문자열", "String"],
  ["hash_table", "core_data_structure", "해시 테이블", "Hash table"],
  ["stack", "core_data_structure", "스택", "Stack"],
  ["queue", "core_data_structure", "큐", "Queue"],
  ["heap", "core_data_structure", "힙", "Heap"],
  ["priority_queue", "core_data_structure", "우선순위 큐", "Priority queue"],
  ["linked_list", "core_data_structure", "연결 리스트", "Linked list"],
  ["tree", "core_data_structure", "트리", "Tree"],
  ["binary_tree", "core_data_structure", "이진 트리", "Binary tree"],
  ["binary_search_tree", "core_data_structure", "이진 탐색 트리", "Binary search tree"],
  ["trie", "core_data_structure", "트라이", "Trie"],
  ["matrix", "core_data_structure", "행렬", "Matrix"],
  ["set", "core_data_structure", "집합", "Set"],
  ["ordered_set", "advanced_structure", "정렬 집합", "Ordered set"],
  ["segment_tree", "advanced_structure", "세그먼트 트리", "Segment tree"],
  ["binary_indexed_tree", "advanced_structure", "펜윅 트리", "Binary indexed tree"],
  ["monotonic_stack", "advanced_structure", "모노토닉 스택", "Monotonic stack"],
  ["monotonic_queue", "advanced_structure", "모노토닉 큐", "Monotonic queue"],
  ["deque", "advanced_structure", "덱", "Deque"],
  ["sorting", "ordering_scanning", "정렬", "Sorting"],
  ["binary_search", "ordering_scanning", "이분 탐색", "Binary search"],
  ["two_pointers", "ordering_scanning", "투 포인터", "Two pointers"],
  ["sliding_window", "ordering_scanning", "슬라이딩 윈도우", "Sliding window"],
  ["prefix_sum", "ordering_scanning", "누적합", "Prefix sum"],
  ["difference_array", "ordering_scanning", "차분 배열", "Difference array"],
  ["sweep_line", "ordering_scanning", "스위프 라인", "Sweep line"],
  ["intervals", "ordering_scanning", "구간 처리", "Intervals"],
  ["merge_intervals", "ordering_scanning", "구간 병합", "Merge intervals"],
  ["quickselect", "ordering_scanning", "퀵셀렉트", "Quickselect"],
  ["graph", "graph_search", "그래프", "Graph"],
  ["dfs", "graph_search", "DFS", "DFS"],
  ["bfs", "graph_search", "BFS", "BFS"],
  ["graph_traversal", "graph_search", "그래프 탐색", "Graph traversal"],
  ["dijkstra", "graph_search", "다익스트라", "Dijkstra"],
  ["shortest_path", "graph_search", "최단 경로", "Shortest path"],
  ["bellman_ford", "graph_search", "벨만-포드", "Bellman-Ford"],
  ["floyd_warshall", "graph_search", "플로이드-워셜", "Floyd-Warshall"],
  ["union_find", "graph_search", "유니온 파인드", "Union-Find"],
  ["topological_sort", "graph_search", "위상 정렬", "Topological sort"],
  ["minimum_spanning_tree", "graph_search", "최소 신장 트리", "Minimum spanning tree"],
  ["strongly_connected_component", "graph_search", "강결합 컴포넌트", "Strongly connected component"],
  ["dynamic_programming", "optimization_strategy", "동적 계획법", "Dynamic programming"],
  ["memoization", "optimization_strategy", "메모이제이션", "Memoization"],
  ["greedy", "optimization_strategy", "그리디", "Greedy"],
  ["backtracking", "optimization_strategy", "백트래킹", "Backtracking"],
  ["recursion", "optimization_strategy", "재귀", "Recursion"],
  ["divide_and_conquer", "optimization_strategy", "분할 정복", "Divide and conquer"],
  ["branch_and_bound", "optimization_strategy", "분기 한정", "Branch and bound"],
  ["bitmask_dp", "optimization_strategy", "비트마스크 DP", "Bitmask DP"],
  ["math", "math_counting", "수학", "Math"],
  ["number_theory", "math_counting", "정수론", "Number theory"],
  ["combinatorics", "math_counting", "조합론", "Combinatorics"],
  ["probability_statistics", "math_counting", "확률과 통계", "Probability and statistics"],
  ["geometry", "math_counting", "기하", "Geometry"],
  ["bit_manipulation", "math_counting", "비트 조작", "Bit manipulation"],
  ["counting", "math_counting", "카운팅", "Counting"],
  ["simulation", "simulation_design", "시뮬레이션", "Simulation"],
  ["design", "simulation_design", "설계", "Design"],
  ["implementation", "simulation_design", "구현", "Implementation"],
  ["game_theory", "simulation_design", "게임 이론", "Game theory"],
  ["interactive", "simulation_design", "인터랙티브", "Interactive"],
  ["data_stream", "simulation_design", "데이터 스트림", "Data stream"],
  ["sql_select", "sql", "SQL SELECT", "SQL SELECT"],
  ["sql_aggregation", "sql", "SQL 집계", "SQL aggregation"],
  ["sql_group_by", "sql", "SQL GROUP BY", "SQL GROUP BY"],
  ["sql_join", "sql", "SQL JOIN", "SQL JOIN"],
  ["sql_null", "sql", "SQL NULL", "SQL NULL"],
  ["sql_string_date", "sql", "SQL 문자열/날짜", "SQL string/date"],
  ["sql_subquery", "sql", "SQL 서브쿼리", "SQL subquery"],
  ["sql_window_function", "sql", "SQL 윈도우 함수", "SQL window function"]
];

export const PROBLEM_TYPE_TAGS = SPECS.map(([id, group, ko, en]) => ({
  id,
  group,
  label: { ko, en },
  description: {
    ko: `${ko} 유형의 문제인지 분류합니다.`,
    en: `Classifies the problem as a ${en} type.`
  }
}));
